dist: trusty
sudo: required

language: c

before_install:
  - eval "${MATRIX_EVAL}"
  - go get github.com/freeekanayaka/gh-asset
  - wget https://github.com/libuv/libuv/archive/v1.22.0.tar.gz
  - tar -xzvf v1.22.0.tar.gz
  - pushd libuv-1.22.0 && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
  - sqlite_tmp_dir=/tmp/sqlite
  - $GOPATH/bin/gh-asset -d $sqlite_tmp_dir -x CanonicalLtd sqlite "sqlite-amd64--enable-debug-.*.tar.gz"
  - sudo cp $sqlite_tmp_dir/libsqlite3.so.* /usr/lib/x86_64-linux-gnu
  - sudo cp $sqlite_tmp_dir/sqlite3.h /usr/include/sqlite3.h

script:
  - autoreconf -i
  - ./configure --enable-debug
  - make
  - make ./dqlite-test
  - ./dqlite-test

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - lcov
            - golang
      env:
         - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

after_success:
  - bash <(curl -s https://codecov.io/bash)
