dist: trusty
sudo: false

language: go

addons:
  apt:
    packages:
    - realpath

before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - mkdir -p $GOPATH/src/github.com/hashicorp/raft
  - git clone -b fix-inmem-snapshot-open-twice https://github.com/freeekanayaka/raft.git $GOPATH/src/github.com/hashicorp/raft

script:
  - make dependencies
  - make build
  - make coverage
  - $GOPATH/bin/goveralls -coverprofile overalls.coverprofile -service=travis-ci

go:
  - 1.9
