dist: trusty
sudo: required

language: c

addons:
  apt:
    packages:
    - lcov

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://github.com/libuv/libuv/archive/v1.22.0.tar.gz
  - tar -xzvf v1.22.0.tar.gz
  - pushd libuv-1.22.0 && sh autogen.sh && ./configure --prefix=/usr && make && sudo make install && popd
  - curl -L https://api.github.com/repos/CanonicalLtd/sqlite/tarball/wal-replication > sqlite.tar.gz
  - tar -xzvf sqlite.tar.gz
  - pushd CanonicalLtd-sqlite-3be11a5 && git log -1 --format=format:%ci%n | sed -e 's/ [-+].*$//;s/ /T/;s/^/D /' > manifest && echo $(git log -1 --format=format:%H) > manifest.uuid && ./configure --enable-wal-replication --enable-debug --disable-amalgamation --prefix=/usr/ --libdir=/usr/lib/$(uname -p)-linux-gnu && make && sudo make install && popd

script:
  - autoreconf -i
  - ./configure --enable-debug
  - make
  - make ./dqlite-test
  - ./dqlite-test

compiler:
  - gcc

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

after_success:
  - bash <(curl -s https://codecov.io/bash)
