dist: xenial
language: c
addons:
  apt:
    sources:
    - sourceline: 'ppa:dqlite-maintainers/master'
    packages:
    - lcov
    - libsqlite3-dev
    - libuv1-dev
    - libco-dev
    - libraft-dev
compiler:
  - gcc
script:
  - autoreconf -i
  - ./configure --enable-debug --enable-code-coverage --enable-sanitize
  - CFLAGS=-O0
  - make
  - make check || cat ./test-suite.log
  - if [ $TRAVIS_COMPILER = gcc ]; then make code-coverage-capture; fi
after_success:
  - bash <(curl -s https://codecov.io/bash) -g "./test*"
