dist: trusty
sudo: false

language: go

before_install:
  - go get github.com/go-playground/overalls
  - go get github.com/mattn/goveralls
  - mkdir -p $GOPATH/src/github.com/armon/
  - git clone -b go-1.6-and-1.7-compatibility https://github.com/freeekanayaka/go-metrics.git $GOPATH/src/github.com/armon/go-metrics

script:
  - make dependencies
  - make build
  - make coverage
  - $GOPATH/bin/goveralls -coverprofile overalls.coverprofile -service=travis-ci

go:
  - 1.8
  - 1.9
